### PR TITLE
Check for existing la_grp in after_save callback

### PR DESCRIPTION
**Pull request by mark-cooper**

### CODE REVIEW

**Review by Blake- — APPROVED** [review]

**Comment by Blake-** [comment]
@mark-cooper 

`[2023-02-27T18:18:25-05:00] (lonearranger) /archivesspace/gems/gems/rufus-scheduler-2.0.24/lib/rufus/sc/cronline.rb:80: warning: constant ::Fixnum is deprecated
[2023-02-27T18:18:27-05:00] (lonearranger) I, [2023-02-27T17:18:27.496792 #76]  INFO -- : Thread-2002: Updating system preferences
[2023-02-27T18:18:28-05:00] (lonearranger) I, [2023-02-27T17:18:28.232550 #76]  INFO -- : Thread-2002:
[2023-02-27T18:18:28-05:00] (lonearranger) ~~~ ASPACE REQUESTS PLUGIN ENABLED ~~~
[2023-02-27T18:18:28-05:00] (lonearranger)       ========================================================================
[2023-02-27T18:18:28-05:00] (lonearranger)       A trace file has been written to the following location: /archivesspace/data/tmp/aspace_diagnostic_1677539908.txt
[2023-02-27T18:18:28-05:00] (lonearranger)       This file contains information that will assist developers in diagnosing
[2023-02-27T18:18:28-05:00] (lonearranger)       problems with your ArchivesSpace installation.  Please review the file's
[2023-02-27T18:18:28-05:00] (lonearranger)       contents for sensitive information (such as passwords) that you might not
[2023-02-27T18:18:28-05:00] (lonearranger)       want to share.
[2023-02-27T18:18:28-05:00] (lonearranger)       ========================================================================
[2023-02-27T18:18:28-05:00] (lonearranger) Feb 27, 2023 5:18:28 PM org.eclipse.jetty.server.handler.ContextHandler$Context log
[2023-02-27T18:18:28-05:00] (lonearranger) INFO: An exception happened during JRuby-Rack startup
[2023-02-27T18:18:28-05:00] (lonearranger) undefined method `long_arranger_group' for #<Repository:0x532860c7>
[2023-02-27T18:18:28-05:00] (lonearranger) Did you mean?  lone_arranger_group
[2023-02-27T18:18:28-05:00] (lonearranger) --- System
[2023-02-27T18:18:28-05:00] (lonearranger) jruby 9.2.20.1 (2.5.8) 2021-11-30 2a2962fbd1 OpenJDK 64-Bit Server VM 11.0.16+8-post-Ubuntu-0ubuntu120.04 on 11.0.16+8-post-Ubuntu-0ubuntu120.04 +jit [linux-x86_64]
[2023-02-27T18:18:28-05:00] (lonearranger) Time: 2023-02-27 17:18:28 -0600
[2023-02-27T18:18:28-05:00] (lonearranger) Server: jetty/9.4.44.v20210927
[2023-02-27T18:18:28-05:00] (lonearranger) jruby.home: uri:classloader://META-INF/jruby.home
[2023-02-27T18:18:28-05:00] (lonearranger) --- Context Init Parameters:
[2023-02-27T18:18:28-05:00] (lonearranger) jruby.max.runtimes = 1
[2023-02-27T18:18:28-05:00] (lonearranger) jruby.min.runtimes = 1
[2023-02-27T18:18:28-05:00] (lonearranger) public.root = /
[2023-02-27T18:18:28-05:00] (lonearranger) rack.env = production
[2023-02-27T18:18:28-05:00] (lonearranger) --- Backtrace
[2023-02-27T18:18:28-05:00] (lonearranger) NoMethodError: undefined method `long_arranger_group' for #<Repository:0x532860c7>
[2023-02-27T18:18:28-05:00] (lonearranger) Did you mean?  lone_arranger_group
[2023-02-27T18:18:28-05:00] (lonearranger)                         <main> at /archivesspace/plugins/lone_arranger/backend/plugin_init.rb:11
[2023-02-27T18:18:28-05:00] (lonearranger)                           each at /archivesspace/gems/gems/sequel-5.9.0/lib/sequel/dataset/actions.rb:149
[2023-02-27T18:18:28-05:00] (lonearranger)             process_result_set at /archivesspace/gems/gems/sequel-5.9.0/lib/sequel/adapters/jdbc.rb:795
[2023-02-27T18:18:28-05:00] (lonearranger)                     fetch_rows at /archivesspace/gems/gems/sequel-5.9.0/lib/sequel/adapters/jdbc.rb:726
[2023-02-27T18:18:28-05:00] (lonearranger)                        execute at /archivesspace/gems/gems/sequel-5.9.0/lib/sequel/adapters/jdbc.rb:244
[2023-02-27T18:18:28-05:00] (lonearranger)                      statement at /archivesspace/gems/gems/sequel-5.9.0/lib/sequel/adapters/jdbc.rb:675
[2023-02-27T18:18:28-05:00] (lonearranger)                        execute at /archivesspace/gems/gems/sequel-5.9.0/lib/sequel/adapters/jdbc.rb:239
[2023-02-27T18:18:28-05:00] (lonearranger)                           hold at /archivesspace/gems/gems/sequel-5.9.0/lib/sequel/connection_pool/threaded.rb:87
[2023-02-27T18:18:28-05:00] (lonearranger)                    synchronize at /archivesspace/gems/gems/sequel-5.9.0/lib/sequel/database/connecting.rb:270
[2023-02-27T18:18:28-05:00] (lonearranger)                        execute at /archivesspace/gems/gems/sequel-5.9.0/lib/sequel/adapters/jdbc.rb:238
[2023-02-27T18:18:28-05:00] (lonearranger)                        execute at /archivesspace/gems/gems/sequel-5.9.0/lib/sequel/dataset/actions.rb:1082
[2023-02-27T18:18:28-05:00] (lonearranger)                     fetch_rows at /archivesspace/gems/gems/sequel-5.9.0/lib/sequel/adapters/jdbc.rb:726
[2023-02-27T18:18:28-05:00] (lonearranger)                           each at /archivesspace/gems/gems/sequel-5.9.0/lib/sequel/dataset/actions.rb:149
[2023-02-27T18:18:28-05:00] (lonearranger)                           each at /archivesspace/gems/gems/sequel-5.9.0/lib/sequel/model/plugins.rb:33
[2023-02-27T18:18:28-05:00] (lonearranger)                         <main> at /archivesspace/plugins/lone_arranger/backend/plugin_init.rb:6
[2023-02-27T18:18:28-05:00] (lonearranger)                    loaded_hook at /archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-18130848535189203675/webapp/WEB-INF/app/main.rb:63
[2023-02-27T18:18:28-05:00] (lonearranger)                         <main> at /archivesspace/plugins/lone_arranger/backend/plugin_init.rb:5
[2023-02-27T18:18:28-05:00] (lonearranger)                           load at org/jruby/RubyKernel.java:1009
[2023-02-27T18:18:28-05:00] (lonearranger)           ArchivesSpaceService at /archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-18130848535189203675/webapp/WEB-INF/app/main.rb:245
[2023-02-27T18:18:28-05:00] (lonearranger)                           each at org/jruby/RubyArray.java:1821
[2023-02-27T18:18:28-05:00] (lonearranger)           ArchivesSpaceService at /archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-18130848535189203675/webapp/WEB-INF/app/main.rb:242
[2023-02-27T18:18:28-05:00] (lonearranger)                           open at /archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-18130848535189203675/webapp/WEB-INF/app/model/db.rb:210
[2023-02-27T18:18:28-05:00] (lonearranger)                    transaction at /archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-18130848535189203675/webapp/WEB-INF/app/model/db.rb:101
[2023-02-27T18:18:28-05:00] (lonearranger)                   _transaction at /archivesspace/gems/gems/sequel-5.9.0/lib/sequel/database/transactions.rb:204
[2023-02-27T18:18:28-05:00] (lonearranger)                    transaction at /archivesspace/gems/gems/sequel-5.9.0/lib/sequel/database/transactions.rb:179
[2023-02-27T18:18:28-05:00] (lonearranger)                           hold at /archivesspace/gems/gems/sequel-5.9.0/lib/sequel/connection_pool/threaded.rb:91
[2023-02-27T18:18:28-05:00] (lonearranger)                    synchronize at /archivesspace/gems/gems/sequel-5.9.0/lib/sequel/database/connecting.rb:270
[2023-02-27T18:18:28-05:00] (lonearranger)                    transaction at /archivesspace/gems/gems/sequel-5.9.0/lib/sequel/database/transactions.rb:145
[2023-02-27T18:18:28-05:00] (lonearranger)                    transaction at /archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-18130848535189203675/webapp/WEB-INF/app/model/db.rb:100
[2023-02-27T18:18:28-05:00] (lonearranger)                           open at /archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-18130848535189203675/webapp/WEB-INF/app/model/db.rb:207
[2023-02-27T18:18:28-05:00] (lonearranger)                           open at /archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-18130848535189203675/webapp/WEB-INF/app/model/db.rb:204
[2023-02-27T18:18:28-05:00] (lonearranger)                           open at /archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-18130848535189203675/webapp/WEB-INF/app/model/db.rb:542
[2023-02-27T18:18:28-05:00] (lonearranger)           ArchivesSpaceService at /archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-18130848535189203675/webapp/WEB-INF/app/main.rb:224
[2023-02-27T18:18:28-05:00] (lonearranger)                      configure at /archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1426
[2023-02-27T18:18:28-05:00] (lonearranger)   <class:ArchivesSpaceService> at /archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-18130848535189203675/webapp/WEB-INF/app/main.rb:101
[2023-02-27T18:18:28-05:00] (lonearranger)                         <main> at /archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-18130848535189203675/webapp/WEB-INF/app/main.rb:48
[2023-02-27T18:18:28-05:00] (lonearranger)                        require at org/jruby/RubyKernel.java:974
[2023-02-27T18:18:28-05:00] (lonearranger)                        require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:83
[2023-02-27T18:18:28-05:00] (lonearranger)                         <main> at /archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-18130848535189203675/webapp/WEB-INF/config.ru:4
[2023-02-27T18:18:28-05:00] (lonearranger)                  instance_eval at org/jruby/RubyBasicObject.java:2622
[2023-02-27T18:18:28-05:00] (lonearranger)                     initialize at uri:classloader:/vendor/rack-2.2.3/rack/builder.rb:125
[2023-02-27T18:18:28-05:00] (lonearranger)                         <main> at /archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-18130848535189203675/webapp/WEB-INF/config.ru:1
[2023-02-27T18:18:28-05:00] (lonearranger)                   start_server at launcher/launcher.rb:90
[2023-02-27T18:18:28-05:00] (lonearranger)                           main at launcher/launcher.rb:144
[2023-02-27T18:18:28-05:00] (lonearranger)                         <main> at launcher/launcher.rb:242
[2023-02-27T18:18:28-05:00] (lonearranger) --- RubyGems
[2023-02-27T18:18:28-05:00] (lonearranger) Gem.dir: /archivesspace/gems
[2023-02-27T18:18:28-05:00] (lonearranger) Gem.path:
[2023-02-27T18:18:28-05:00] (lonearranger) uri:classloader:/META-INF/jruby.home/lib/ruby/gems/shared
[2023-02-27T18:18:28-05:00] (lonearranger) /archivesspace/gems
[2023-02-27T18:18:28-05:00] (lonearranger) Activated gems:
[2023-02-27T18:18:28-05:00] (lonearranger)   did_you_mean-1.2.1
[2023-02-27T18:18:28-05:00] (lonearranger)   fileutils-1.1.0
[2023-02-27T18:18:28-05:00] (lonearranger)   bundler-2.1.4
[2023-02-27T18:18:28-05:00] (lonearranger)   concurrent-ruby-1.1.9
[2023-02-27T18:18:28-05:00] (lonearranger)   i18n-0.9.1
[2023-02-27T18:18:28-05:00] (lonearranger)   minitest-5.14.4
[2023-02-27T18:18:28-05:00] (lonearranger)   thread_safe-0.3.6-java`

**Comment by mark-cooper** [comment]
@Blake- fixed. Retry should be good.

**Comment by Blake-** [comment]
👍

**Comment by Blake-** [comment]
@mark-cooper it seems to work but it's throwing an error

```
[2023-02-27T18:32:50-05:00] (lonearranger) INFO: Started @48631ms
[2023-02-27T18:32:50-05:00] (lonearranger) ************************************************************
[2023-02-27T18:32:50-05:00] (lonearranger)   Welcome to ArchivesSpace!
[2023-02-27T18:32:50-05:00] (lonearranger)   You can now point your browser to http://localhost:8080
[2023-02-27T18:32:50-05:00] (lonearranger) ************************************************************
[2023-02-27T18:33:10-05:00] (lonearranger) E, [2023-02-27T17:33:10.543969 #74] ERROR -- : Thread-3364: Unhandled exception!
[2023-02-27T18:33:10-05:00] (lonearranger) E, [2023-02-27T17:33:10.705407 #74] ERROR -- :
[2023-02-27T18:33:10-05:00] (lonearranger) uninitialized constant Kernel::RepositoryWithAgent
[2023-02-27T18:33:10-05:00] (lonearranger) org/jruby/RubyModule.java:3766:in `const_missing'
[2023-02-27T18:33:10-05:00] (lonearranger) org/jruby/RubyModule.java:3713:in `const_get'
[2023-02-27T18:33:10-05:00] (lonearranger) /archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-5040165548403658975/webapp/WEB-INF/app/model/active_edit.rb:50:in `block in lock_versions_for'
[2023-02-27T18:33:10-05:00] (lonearranger) org/jruby/RubyArray.java:1821:in `each'
[2023-02-27T18:33:10-05:00] (lonearranger) /archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-5040165548403658975/webapp/WEB-INF/app/model/active_edit.rb:45:in `lock_versions_for'
[2023-02-27T18:33:10-05:00] (lonearranger) /archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-5040165548403658975/webapp/WEB-INF/app/model/active_edit.rb:32:in `update_with'
[2023-02-27T18:33:10-05:00] (lonearranger) /archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-5040165548403658975/webapp/WEB-INF/app/controllers/update_monitor.rb:13:in `block in ArchivesSpaceService'
[2023-02-27T18:33:10-05:00] (lonearranger) org/jruby/RubyBasicObject.java:2622:in `instance_eval'
[2023-02-27T18:33:10-05:00] (lonearranger) /archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-5040165548403658975/webapp/WEB-INF/app/lib/rest.rb:397:in `block in returns'
[2023-02-27T18:33:10-05:00] (lonearranger) /archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-5040165548403658975/webapp/WEB-INF/app/model/db.rb:221:in `block in open'
[2023-02-27T18:33:10-05:00] (lonearranger) /archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-5040165548403658975/webapp/WEB-INF/app/model/db.rb:204:in `open'
[2023-02-27T18:33:10-05:00] (lonearranger) /archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-5040165548403658975/webapp/WEB-INF/app/model/db.rb:542:in `block in DB'
[2023-02-27T18:33:10-05:00] (lonearranger) /archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-5040165548403658975/webapp/WEB-INF/app/lib/rest.rb:380:in `block in returns'
[2023-02-27T18:33:10-05:00] (lonearranger) /archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-5040165548403658975/webapp/WEB-INF/app/lib/request_context.rb:24:in `open'
[2023-02-27T18:33:10-05:00] (lonearranger) /archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-5040165548403658975/webapp/WEB-INF/app/lib/rest.rb:348:in `block in returns'
[2023-02-27T18:33:10-05:00] (lonearranger) org/jruby/RubyMethod.java:115:in `call'
[2023-02-27T18:33:10-05:00] (lonearranger) /archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1635:in `block in compile!'
[2023-02-27T18:33:10-05:00] (lonearranger) /archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:992:in `block in route!'
[2023-02-27T18:33:10-05:00] (lonearranger) /archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1011:in `route_eval'
[2023-02-27T18:33:10-05:00] (lonearranger) /archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:992:in `block in route!'
[2023-02-27T18:33:10-05:00] (lonearranger) /archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1040:in `block in process_route'
[2023-02-27T18:33:10-05:00] (lonearranger) org/jruby/RubyKernel.java:1189:in `catch'
[2023-02-27T18:33:10-05:00] (lonearranger) /archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1038:in `process_route'
[2023-02-27T18:33:10-05:00] (lonearranger) /archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:990:in `block in route!'
[2023-02-27T18:33:10-05:00] (lonearranger) org/jruby/RubyArray.java:1821:in `each'
[2023-02-27T18:33:10-05:00] (lonearranger) /archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:989:in `route!'
[2023-02-27T18:33:10-05:00] (lonearranger) /archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1097:in `block in dispatch!'
[2023-02-27T18:33:10-05:00] (lonearranger) /archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `block in invoke'
[2023-02-27T18:33:10-05:00] (lonearranger) org/jruby/RubyKernel.java:1189:in `catch'
[2023-02-27T18:33:10-05:00] (lonearranger) /archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `invoke'
[2023-02-27T18:33:10-05:00] (lonearranger) /archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1094:in `dispatch!'
[2023-02-27T18:33:10-05:00] (lonearranger) /archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:924:in `block in call!'
[2023-02-27T18:33:10-05:00] (lonearranger) /archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `block in invoke'
[2023-02-27T18:33:10-05:00] (lonearranger) org/jruby/RubyKernel.java:1189:in `catch'
[2023-02-27T18:33:10-05:00] (lonearranger) /archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `invoke'
[2023-02-27T18:33:10-05:00] (lonearranger) /archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:924:in `call!'
[2023-02-27T18:33:10-05:00] (lonearranger) /archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:913:in `call'
[2023-02-27T18:33:10-05:00] (lonearranger) /archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-5040165548403658975/webapp/WEB-INF/app/main.rb:335:in `call'
[2023-02-27T18:33:10-05:00] (lonearranger) /archivesspace/gems/gems/rack-protection-2.0.5/lib/rack/protection/xss_header.rb:18:in `call'
[2023-02-27T18:33:10-05:00] (lonearranger) /archivesspace/gems/gems/rack-protection-2.0.5/lib/rack/protection/path_traversal.rb:16:in `call'
[2023-02-27T18:33:10-05:00] (lonearranger) /archivesspace/gems/gems/rack-protection-2.0.5/lib/rack/protection/json_csrf.rb:26:in `call'
[2023-02-27T18:33:10-05:00] (lonearranger) /archivesspace/gems/gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call'
[2023-02-27T18:33:10-05:00] (lonearranger) /archivesspace/gems/gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call'
[2023-02-27T18:33:10-05:00] (lonearranger) /archivesspace/gems/gems/rack-protection-2.0.5/lib/rack/protection/frame_options.rb:31:in `call'
[2023-02-27T18:33:10-05:00] (lonearranger) uri:classloader:/vendor/rack-2.2.3/rack/null_logger.rb:11:in `call'
[2023-02-27T18:33:10-05:00] (lonearranger) uri:classloader:/vendor/rack-2.2.3/rack/head.rb:12:in `call'
[2023-02-27T18:33:10-05:00] (lonearranger) /archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:194:in `call'
[2023-02-27T18:33:10-05:00] (lonearranger) /archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1957:in `call'
[2023-02-27T18:33:10-05:00] (lonearranger) /archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1502:in `block in call'
[2023-02-27T18:33:10-05:00] (lonearranger) /archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1729:in `synchronize'
[2023-02-27T18:33:10-05:00] (lonearranger) /archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1502:in `call'
[2023-02-27T18:33:10-05:00] (lonearranger) uri:classloader:/vendor/rack-2.2.3/rack/urlmap.rb:74:in `block in call'
[2023-02-27T18:33:10-05:00] (lonearranger) org/jruby/RubyArray.java:1821:in `each'
[2023-02-27T18:33:10-05:00] (lonearranger) uri:classloader:/vendor/rack-2.2.3/rack/urlmap.rb:58:in `call'
[2023-02-27T18:33:10-05:00] (lonearranger) uri:classloader:/rack/handler/servlet.rb:22:in `call'
[2023-02-27T18:33:10-05:00] (lonearranger) warning: thread "Ruby-3-Thread-3: /archivesspace/data/tmp/jetty-0_0_0_0-8080-frontend_war-_-any-3211929907426913940/webapp/WEB-INF/app/models/edit_mediator.rb:109" terminated with exception (report_on_exception is true):
[2023-02-27T18:33:10-05:00] (lonearranger) Exception: Unknown response: {"error":"uninitialized constant Kernel::RepositoryWithAgent: org/jruby/RubyModule.java:3766:in `const_missing'\n\torg/jruby/RubyModule.java:3713:in `const_get'\n\t/archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-5040165548403658975/webapp/WEB-INF/app/model/active_edit.rb:50:in `block in lock_versions_for'\n\torg/jruby/RubyArray.java:1821:in `each'\n\t/archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-5040165548403658975/webapp/WEB-INF/app/model/active_edit.rb:45:in `lock_versions_for'\n\t/archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-5040165548403658975/webapp/WEB-INF/app/model/active_edit.rb:32:in `update_with'\n\t/archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-5040165548403658975/webapp/WEB-INF/app/controllers/update_monitor.rb:13:in `block in ArchivesSpaceService'\n\torg/jruby/RubyBasicObject.java:2622:in `instance_eval'\n\t/archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-5040165548403658975/webapp/WEB-INF/app/lib/rest.rb:397:in `block in returns'\n\t/archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-5040165548403658975/webapp/WEB-INF/app/model/db.rb:221:in `block in open'\n\t/archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-5040165548403658975/webapp/WEB-INF/app/model/db.rb:204:in `open'\n\t/archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-5040165548403658975/webapp/WEB-INF/app/model/db.rb:542:in `block in DB'\n\t/archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-5040165548403658975/webapp/WEB-INF/app/lib/rest.rb:380:in `block in returns'\n\t/archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-5040165548403658975/webapp/WEB-INF/app/lib/request_context.rb:24:in `open'\n\t/archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-5040165548403658975/webapp/WEB-INF/app/lib/rest.rb:348:in `block in returns'\n\torg/jruby/RubyMethod.java:115:in `call'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1635:in `block in compile!'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:992:in `block in route!'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1011:in `route_eval'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:992:in `block in route!'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1040:in `block in process_route'\n\torg/jruby/RubyKernel.java:1189:in `catch'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1038:in `process_route'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:990:in `block in route!'\n\torg/jruby/RubyArray.java:1821:in `each'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:989:in `route!'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1097:in `block in dispatch!'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `block in invoke'\n\torg/jruby/RubyKernel.java:1189:in `catch'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `invoke'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1094:in `dispatch!'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:924:in `block in call!'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `block in invoke'\n\torg/jruby/RubyKernel.java:1189:in `catch'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `invoke'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:924:in `call!'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:913:in `call'\n\t/archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-5040165548403658975/webapp/WEB-INF/app/main.rb:335:in `call'\n\t/archivesspace/gems/gems/rack-protection-2.0.5/lib/rack/protection/xss_header.rb:18:in `call'\n\t/archivesspace/gems/gems/rack-protection-2.0.5/lib/rack/protection/path_traversal.rb:16:in `call'\n\t/archivesspace/gems/gems/rack-protection-2.0.5/lib/rack/protection/json_csrf.rb:26:in `call'\n\t/archivesspace/gems/gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call'\n\t/archivesspace/gems/gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call'\n\t/archivesspace/gems/gems/rack-protection-2.0.5/lib/rack/protection/frame_options.rb:31:in `call'\n\turi:classloader:/vendor/rack-2.2.3/rack/null_logger.rb:11:in `call'\n\turi:classloader:/vendor/rack-2.2.3/rack/head.rb:12:in `call'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:194:in `call'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1957:in `call'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1502:in `block in call'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1729:in `synchronize'\n\t/archivesspace/gems/gems/sinatra-2.0.5/lib/sinatra/base.rb:1502:in `call'\n\turi:classloader:/vendor/rack-2.2.3/rack/urlmap.rb:74:in `block in call'\n\torg/jruby/RubyArray.java:1821:in `each'\n\turi:classloader:/vendor/rack-2.2.3/rack/urlmap.rb:58:in `call'\n\turi:classloader:/rack/handler/servlet.rb:22:in `call'"}
[2023-02-27T18:33:10-05:00] (lonearranger)  (code: 500)
[2023-02-27T18:33:10-05:00] (lonearranger)                       save at uri:classloader:/jsonmodel_client.rb:348
[2023-02-27T18:33:10-05:00] (lonearranger)   synchronise_with_backend at /archivesspace/data/tmp/jetty-0_0_0_0-8080-frontend_war-_-any-3211929907426913940/webapp/WEB-INF/app/models/edit_mediator.rb:100
[2023-02-27T18:33:10-05:00] (lonearranger)                      start at /archivesspace/data/tmp/jetty-0_0_0_0-8080-frontend_war-_-any-3211929907426913940/webapp/WEB-INF/app/models/edit_mediator.rb:117
q
```

**Comment by mark-cooper** [comment]
That looks like stale data. You could try logging out, clearing cache and back in. Everything ok?

**Pull request merged**
